# Cargo Deny configuration
# https://embarkstudios.github.io/cargo-deny/

[advisories]
db-path = "$CARGO_HOME/cargo-deny"
db-urls = ["https://github.com/rustsec/advisory-db/raw/main/db.json"]
severity-threshold = "low"
ignore = [
    #"RUSTSEC-2021-0001",
]

[licenses]
confidence-threshold = 0.8
copyleft = "warn"
allow-osi-fsf-free = "both"
default = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
]
deny = [
    "GPL-2.0",
    "GPL-3.0",
    "AGPL-3.0",
]
exceptions = [
]

[bans]
multiple-versions = "warn"
highlight = "all"
allow = [
]
deny = [
    { name = "openssl" },
]
skip = [
]

[sources]
# Lint level for what to happen when a crate from a crate registry that is not in the allow list is detected
unknown-registry = "warn"
# Lint level for what to happen when a crate from a git repository that is not in the allow list is detected
unknown-git = "warn"
# A list of allowed crate registries containing allowed crates
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
# A list of allowed Git repositories containing allowed crates
allow-git = []
